services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: loginanomaly-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - loginanomaly_sqldata:/var/opt/mssql

volumes:
  loginanomaly_sqldata: